# Generated by Django 6.0.5 on 2026-05-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=20, unique=True, verbose_name='کد ملی / شناسه اقتصادی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('person_type', models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], max_length=10, verbose_name='نوع شخص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
            },
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سنگ')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('size', models.CharField(max_length=50, verbose_name='ابعاد')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت خرید')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت فروش')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'سنگ',
                'verbose_name_plural': 'سنگ ها',
            },
        ),
        migrations.CreateModel(
            name='StoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='دسته بندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته سنگ',
                'verbose_name_plural': 'دسته های سنگ',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام واحد')),
                ('symbol', models.CharField(max_length=20, verbose_name='نماد واحد')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحدها',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='سمت')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='حقوق')),
                ('hire_date', models.DateField(verbose_name='تاریخ استخدام')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=30, unique=True, verbose_name='کد مشتری')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='تاریخ خرید')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ کل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='تاریخ فروش')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ کل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='مشتری')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قیمت کل')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale', verbose_name='فروش')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stone', verbose_name='سنگ')),
            ],
            options={
                'verbose_name': 'آیتم فروش',
                'verbose_name_plural': 'آیتم های فروش',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قیمت کل')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchase', verbose_name='خرید')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stone', verbose_name='سنگ')),
            ],
            options={
                'verbose_name': 'آیتم خرید',
                'verbose_name_plural': 'آیتم های خرید',
            },
        ),
        migrations.CreateModel(
            name='StoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نوع سنگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stonecategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'نوع سنگ',
                'verbose_name_plural': 'انواع سنگ',
            },
        ),
        migrations.AddField(
            model_name='stone',
            name='stone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stonetype', verbose_name='نوع سنگ'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'تامین کننده',
                'verbose_name_plural': 'تامین کنندگان',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='تامین کننده'),
        ),
        migrations.AddField(
            model_name='stone',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='واحد'),
        ),
    ]
